//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace lpubsppop01.AnyFilterVSIX.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lpubsppop01.AnyFilterVSIX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arguments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Arguments {
            get {
                return ResourceManager.GetString("Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diff に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff {
            get {
                return ResourceManager.GetString("Diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input Encoding に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputEncoding {
            get {
                return ResourceManager.GetString("InputEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert output text after current line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InsertOutputTextAfterCurrentLine {
            get {
                return ResourceManager.GetString("InsertOutputTextAfterCurrentLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output Encoding に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OutputEncoding {
            get {
                return ResourceManager.GetString("OutputEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pass input text to standard input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PassInputTextToStandardInput {
            get {
                return ResourceManager.GetString("PassInputTextToStandardInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   $(InputText), $(InputTempFilePath), $(UserInput), $(UserInputTempFilePath) is available. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ArgumentsHint {
            get {
                return ResourceManager.GetString("Settings_ArgumentsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   $(InputText), $(UserInput) is available in template file content. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_TemplateFilePathHint {
            get {
                return ResourceManager.GetString("Settings_TemplateFilePathHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Emacs like keybindings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UseEmacsLikeKeybindings {
            get {
                return ResourceManager.GetString("UseEmacsLikeKeybindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use input template file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UseInputTemplateFile {
            get {
                return ResourceManager.GetString("UseInputTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   $(UserInput) will be replaced by this text. Shift+Enter to newline. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserInput_UserInputTextHint {
            get {
                return ResourceManager.GetString("UserInput_UserInputTextHint", resourceCulture);
            }
        }
    }
}
